// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cypherlabdev/odds-optimizer-service/internal/service (interfaces: Cache)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/mock_cache.go -package=mocks github.com/cypherlabdev/odds-optimizer-service/internal/service Cache
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/cypherlabdev/odds-optimizer-service/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockCache is a mock of Cache interface.
type MockCache struct {
	ctrl     *gomock.Controller
	recorder *MockCacheMockRecorder
	isgomock struct{}
}

// MockCacheMockRecorder is the mock recorder for MockCache.
type MockCacheMockRecorder struct {
	mock *MockCache
}

// NewMockCache creates a new mock instance.
func NewMockCache(ctrl *gomock.Controller) *MockCache {
	mock := &MockCache{ctrl: ctrl}
	mock.recorder = &MockCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCache) EXPECT() *MockCacheMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockCache) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockCacheMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockCache)(nil).Close))
}

// Get mocks base method.
func (m *MockCache) Get(ctx context.Context, eventID, market, selection string) (*models.OptimizedOdds, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, eventID, market, selection)
	ret0, _ := ret[0].(*models.OptimizedOdds)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCacheMockRecorder) Get(ctx, eventID, market, selection any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCache)(nil).Get), ctx, eventID, market, selection)
}

// GetByEvent mocks base method.
func (m *MockCache) GetByEvent(ctx context.Context, eventID string) ([]*models.OptimizedOdds, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEvent", ctx, eventID)
	ret0, _ := ret[0].([]*models.OptimizedOdds)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEvent indicates an expected call of GetByEvent.
func (mr *MockCacheMockRecorder) GetByEvent(ctx, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEvent", reflect.TypeOf((*MockCache)(nil).GetByEvent), ctx, eventID)
}

// Ping mocks base method.
func (m *MockCache) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockCacheMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockCache)(nil).Ping), ctx)
}

// Set mocks base method.
func (m *MockCache) Set(ctx context.Context, odds *models.OptimizedOdds) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, odds)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockCacheMockRecorder) Set(ctx, odds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockCache)(nil).Set), ctx, odds)
}

// SetBatch mocks base method.
func (m *MockCache) SetBatch(ctx context.Context, oddsList []*models.OptimizedOdds) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetBatch", ctx, oddsList)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetBatch indicates an expected call of SetBatch.
func (mr *MockCacheMockRecorder) SetBatch(ctx, oddsList any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBatch", reflect.TypeOf((*MockCache)(nil).SetBatch), ctx, oddsList)
}
