// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cypherlabdev/odds-optimizer-service/internal/service (interfaces: Optimizer)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/mock_optimizer.go -package=mocks github.com/cypherlabdev/odds-optimizer-service/internal/service Optimizer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "github.com/cypherlabdev/odds-optimizer-service/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockOptimizer is a mock of Optimizer interface.
type MockOptimizer struct {
	ctrl     *gomock.Controller
	recorder *MockOptimizerMockRecorder
	isgomock struct{}
}

// MockOptimizerMockRecorder is the mock recorder for MockOptimizer.
type MockOptimizerMockRecorder struct {
	mock *MockOptimizer
}

// NewMockOptimizer creates a new mock instance.
func NewMockOptimizer(ctrl *gomock.Controller) *MockOptimizer {
	mock := &MockOptimizer{ctrl: ctrl}
	mock.recorder = &MockOptimizerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOptimizer) EXPECT() *MockOptimizerMockRecorder {
	return m.recorder
}

// BatchOptimize mocks base method.
func (m *MockOptimizer) BatchOptimize(normalized []*models.NormalizedOdds) ([]*models.OptimizedOdds, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchOptimize", normalized)
	ret0, _ := ret[0].([]*models.OptimizedOdds)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchOptimize indicates an expected call of BatchOptimize.
func (mr *MockOptimizerMockRecorder) BatchOptimize(normalized any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchOptimize", reflect.TypeOf((*MockOptimizer)(nil).BatchOptimize), normalized)
}

// Optimize mocks base method.
func (m *MockOptimizer) Optimize(normalized *models.NormalizedOdds) (*models.OptimizedOdds, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Optimize", normalized)
	ret0, _ := ret[0].(*models.OptimizedOdds)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Optimize indicates an expected call of Optimize.
func (mr *MockOptimizerMockRecorder) Optimize(normalized any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Optimize", reflect.TypeOf((*MockOptimizer)(nil).Optimize), normalized)
}
